### PR TITLE
Fix opening on TCP ports on GCE for inlets-pro and update existing firewall-rules if one already exists

### LINKED ISSUE #44: Fix issue with the opening of TCP ports for inlets-pro on GCE
## Expected Behaviour

The GCE operator should open up ports for inlets-pro
For users switching between inlets OSS and inlets-pro, the firewall rules should be 
updated automatically.

## Current Behaviour

If a firewall rule named inlets for inlets OSS already exists, it doesn't open up ports for inlets-pro

## Possible Solution

PR #45 

## Steps to Reproduce (for bugs)

1. Run inletsctl with inlets OSS
2. Run inletsctl again with inlets-pro

### LINKED ISSUE #56: Broken firewall rules for GCE
I think there may be a conflict between the naming for firewall rules for inlets vs inlets-pro, which could lead to issues for users.

First of all I set up a host with OSS, and a firewallRule was created, i.e. for port 8080 I assume

```
alex@alexx:~/dev/sponsors-functions$ inletsctl create --provider gce --zone us-central1-a --project-id $PROJECTID --access-token-file key.json
Using provider: gce
Requesting host: priceless-blackburn2 in us-central1-a, from gce
2020/02/09 09:20:52 inlets firewallRule does not exist
2020/02/09 09:20:52 Creating inlets firewallRule opening port: 8080
Host: priceless-blackburn2|us-central1-a|alexellis, status: active
[1/500] Host: priceless-blackburn2|us-central1-a|alexellis, status: 
[2/500] Host: priceless-blackburn2|us-central1-a|alexellis, status: 
[3/500] Host: priceless-blackburn2|us-central1-a|alexellis, status: 

```

Then I set up a node for inlets-pro, which said the rule already existed:

```
alex@alexx:~/dev/sponsors-functions$ inletsctl create --provider gce --zone us-central1-a --project-id $PROJECTID --access-token-file key.json --remote-tcp localhost
Using provider: gce
Requesting host: objective-khorana7 in us-central1-a, from gce
2020/02/09 09:21:20 inlets firewallRule exists
Host: objective-khorana7|us-central1-a|alexellis, status: active
[1/500] Host: objective-khorana7|us-central1-a|alexellis, status: 
[2/500] Host: objective-khorana7|us-central1-a|alexellis, status: active
```

The problem here is that inlets-pro vs inlets OSS use different ports and so they need separate firewall rules, perhaps with different names too.

Pro: 8123 (auto-tls + control-port), * - any port the client can open

OSS: 8080 - control-port, - 80 - data port

This probably affects inlets-operator too. 

inlets-issue

I actually have no idea how this works, for OSS, since the port `80` should be open and is not.

I forwarded out OpenFaaS and couldn't access it on the public IP, but port 80 was open.

### PR DESCRIPTION
**Pull request by utsavanand2**
Fix opening on TCP ports on GCE for inlets-pro and update existing firewall-rules
if one already exists

Fixes #44
Fixes #56

Signed-off-by: Utsav Anand <utsavanand2@gmail.com>

## Description
This PR will now allow for all TCP traffic through
the inlets-pro exit node
If a firewall-rule for inlets or inlets-pro named 'inlets' already
exists, then it will update the firewall-rule with the
required rules depending on the user using the `--remote-tcp`
flag (inlets-pro) or not in `inletsctl create` command

## How Has This Been Tested?

Here is an unedited screenshot depicting the update of the `inlets` firewall-rule
and the curl to the exit nodes provisioned with inlets-OSS and inlets-pro running
Screenshot 2020-02-09 at 5 14 25 PM
Screenshot 2020-02-09 at 5 09 23 PM
Screenshot 2020-02-09 at 5 13 45 PM

## How are existing users impacted? What migration steps/scripts do we need?
Users will be able to switch between using inlets and inlets-pro through inletsctl without manually updating the firewall rules.

## Checklist:

I have:

- [x] updated the documentation and/or roadmap (if required)
- [x] read the [CONTRIBUTION](https://github.com/inlets/inlets/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`
- [ ] added unit tests

### CODE REVIEW

File: pkg/provision/gce.go [hunk 1]
```diff
@@ -116,53 +108,73 @@ func (p *GCEProvisioner) Provision(host BasicHost) (*ProvisionedHost, error) {
...
+		}
+	} else {
+		firewallRule = &compute.Firewall{
+			Name:        firewallRuleName,
+			Description: "Firewall rule created by inlets-operator",
+			Network:     fmt.Sprintf("projects/%s/global/networks/default", projectID),
+			Allowed: []*compute.FirewallAllowed{
+				{
+					IPProtocol: "tcp",
+					Ports:      []string{controlPort},
```
Comment (alexellis) [inline pkg/provision/gce.go]: I think this is incorrect, it also needs to open port `80`

That's why I had an issue with it and @angelbarrera92 too

Comment (utsavanand2) [reply pkg/provision/gce.go]: But we are aleardy opening the port with the http-server tag on the exit node (every GCE project by default has the http-server flag, privided that the user has not deleted it, it works fine)
Do you want me to create one explicitly?

Comment (utsavanand2) [reply pkg/provision/gce.go]: @alexellis If we're not opening the port 80 then this wouldn't have worked
https://user-images.githubusercontent.com/25264581/74101600-77150a80-4b61-11ea-9e5e-f06653e68309.png

Comment (utsavanand2) [reply pkg/provision/gce.go]: I've added port `80` and `443` to the inlets firewall rule now. I would've added this in the beginning but have been reluctant to do so because the firewall rules in GCE have a priority number (defaults to 1000), I didn't want to create a conflict with some locked down systems where they block ingress with a much lower priority number (means higher priority) and then have inconsistent behaviour. So left this decision to the user assuming most users never delete the default firewall-rules, as we're assuming that the user might not have deleted the `default` network. If a user deletes the `default` network then that would cause problems too.

Comment (alexellis) [reply pkg/provision/gce.go]: `443` is not required because it's not proxied by default for inlets OSS, only 8080 (control) and (80) is what should be done..
